异常处理是Java中唯一正式的错误报告机制，并且通过编译器强制执行。

# 基本异常

异常与普通问题：
所谓普通问题是指，在当前环境下能够得到足够的信息，总能处理这个错误。  
而对于异常情形，就不能继续下去了，因为在当前环境下无法获得必要的信息来解决问题。  
你所能做的就是从当前环境跳出，并且把问题提交给上一级环境。这就是抛出异常时所发生的事情。 

当抛出异常后，有几件事会随之发生。  
首先，同Java中其他对象的创建一样，将使用new在堆上创建异常对象。  
然后，当前的执行路径被终止，并且从当前环境中弹出对异常对象的引用。
此时，异常处理机制接管程序，并开始寻找一个恰当的地方来继续执行程序。
这个恰当的地方就是异常处理程序。  

异常使得我们可以将每件事都当作一个事务来考虑，而异常可以看护着这些事务的底线。

## 异常参数

与使用Java中的其他对象一样，我们总是用new在堆上创建异常对象，这也伴随着存储空间的分配和构造器  
的调用。
所有标准异常类都有两个构造器：
一个是默认构造器，另一个是接受字符串作为参数，以便把相关信息放入异常对象的构造器。

Throwable对象，是异常类型的根类。
错误信息可以保存在异常对象内部或者用异常类的名称来暗示。

#捕获异常

监控区域：一段可能产生异常的代码，并且跟着处理这些异常的代码
## try块
	try{
		//可能产生异常的代码
	}

## 异常处理程序 

异常处理程序：处理抛出的异常的地点，而且针对每个要捕获的异常，得准备相应的处理程序。
异常处理程序紧跟在try块之后，以关键字catch表示：
	
	try{
		//可能产生异常的代码
	}catch(Type1 id1){
		//处理Type1类型的异常
	}catch(Type2 id2){
		//处理Type2类型的异常
	}catch(Type3 id3){
		//处理Type3类型的异常
	}

每个catch子句（异常处理程序）看起来像是接收一个且仅接收一个特殊类型的参数的方法。

当异常被抛出时，异常处理机制将负责搜寻参数与异常类型想匹配的第一个处理程序。  
然后进入catch子句执行，此时认为异常得到了处理。
一旦catch子句结束，则处理程序的查找过程结束。
注意：只有匹配的catch子句才能得到执行。

### 终止与恢复

异常处理理论上有两种基本模型：
* 终止模型
	Java支持终止模型。
* 恢复模型

# 创建自定义异常

要创建自定义异常，必须从已有的异常类继承，最好是选择意思相近的异常类继承。  
建立新的异常类型最简单的方法就是让编译器为你产生默认构造器。

*[InnheritingExceptions.java](src/InnheritingExceptions/src/com/tlxxm/learing/InnheritingExceptions.java)*
	
	package com.tlxxm.learing;
	
	class SimpleException extends Exception{
	
	}
	
	public class InnheritingExceptions {
	    public void f() throws SimpleException{
	        System.out.println("Throw SimpleException from f()");
	        throw new SimpleException();
	    }
	    public static void main(String[] args) {
	        InnheritingExceptions sed=new InnheritingExceptions();
	        try{
	            sed.f();
	        }
	        catch(SimpleException e){
	            System.out.println("捕获异常");
	        }
	    }
	}
**Output：**
>Throw SimpleException from f()  
>捕获异常

编译器创建了默认构造器，它将自动调用基类的默认构造器，也可以创建带参数的构造器。  
但是一般来说，类名就足以说明了。


#异常说明

通过异常说明，以告知某个方法可能抛出的异常类型。

异常说明，它属于方法声明的一部分，紧跟在形式参数列表之后。

异常说明使用了附加的关键字throws，后面接一个所有潜在异常类型的列表。

	void f() throws TooBig,TooSmall,DivZero{}



# 捕获所有异常

通过捕获异常类型的基类Exception，就可以做一这一点。

	catch(Exception e){
	
	}

Exception是与编程有关的所有异常的基类，不会含有太多具体的信息，不过可以调用它从基类
Throwable继承的方法

1. 获取详细信息
	getMessage()
	getLocalizedMessage()  
2. 简单描述
	toString()
3. 调用栈轨迹
	printStackTrace()
	printStackTrace(PrintStream)
	printStackTrace(java.io.PrintWriter)

4. 记录栈帧的当前状态
	fillInStackTrace() 这在程序重新抛出异常时很有用

*[ExceptionMethods.java](src/ExceptionMethods/src/com/tlxxm/learing/ExceptionMethods.java)*
	
	package com.tlxxm.learing;
	
	public class ExceptionMethods {
	
	    public static void main(String[] args) {
	        try{
	            throw new Exception("My Exception");
	        }catch(Exception e){
	            System.out.println("getMessage():"+e.getMessage());
	            System.out.println("getLocalizedMessage():"+e.getLocalizedMessage());
	            System.out.println("toString():"+e.toString());
	            System.out.print("printStackTrace():");
	            e.printStackTrace(System.out);
	        }
	    }
	}
	
**Output：**
>getMessage():My Exception  
>getLocalizedMessage():My Exception  
>toString():java.lang.Exception: My Exception  
>printStackTrace():java.lang.Exception: My Exception  

## 栈轨迹

printStackTrace()提提供的信息，可以通过getStackTrace()方法来直接访问，这个方法将返回一个  
由栈轨迹中的元素所构成的数组，其中每一个元素都表示栈中的一桢。
元素0是栈顶元素，并且是调用序列中的最后一个方法调用（这个Throwable被创建和抛出之处）。

*[WhoCalled.java](src/WhoCalled/src/com/tlxxm/learing/WhoCalled.java)*

	package com.tlxxm.learing;
	
	public class WhoCalled {
	    static void f(){
	        try{
	            throw new Exception();
	        }catch (Exception e){
	            for(StackTraceElement ste : e.getStackTrace())
	                System.out.println(ste.getMethodName());
	        }
	    }
	    static void g(){
	        f();
	    }
	    static void h(){
	        g();
	    }
	    public static void main(String[] args) {
		    f();
		    System.out.println("--------------------------");
		    g();
	        System.out.println("--------------------------");
	        h();
	    }
	}


## 重新抛出异常

	catch(Exception e){
		System.out.println("An exception was thrown")
		throw e;
	}
重新抛出异常会把异常抛出给上一级环境中的异常处理程序，同一个try块的后续catch子句将被忽略。  
如果只是把当前异常对象重新抛出，那么printStackTrace()方法显示的将是原来异常抛出点的调用栈  
信息，而并非重新抛出点的信息。
要想更新这个信息，可以调用fillInStackTrace()方法，这将返回一个Throwable对象，它是通过把  
当前调用栈信息填写原来那个异常对象而建立的。


	catch(Exception e){
		System.out.println("An exception was thrown")
		throw (Exception)e.fillInStackTrace();		
	}

如果使用一个新的异常类型抛出，那么之前的信息就都不会存在了。

## 异常链

异常链：在捕获一个异常后，抛出另一个异常，并且希望把原始异常的信息保存下来。

现在所有的Throwable的子类在构造器中都可以接受一个cause对象作为参数，这个cause表示原始异常。
这样，通过把原始异常传递给新的异常，在新的异常当中，保存原始异常信息。

在Throwable的子类中，只有三种基本的异常类提供了带cause参数的构造器。
Error、Exception、RuntimeException。
如果要把其他类型的异常链接起来，应该使用initCause()方法


#Java 标准异常

Throwable这个类被用来表示任何可以作为异常被抛出的类。

Throwable对象可分为两种类型(子类型)：
* Error
	表示编译时和系统错误，除特殊情况外，一般不用关心
* Exception
	可以被抛出的类型，程序员关心的基类型通常是Exception


# 使用finally进行清理


对于一些代码，可能会希望无论try块中的异常是否抛出，它们都能得到执行。这通常适用于内在回收之外的情况。  
为了达到这个效果，可以在异常处理程序后面加上finally子句。
完整的异常处理程序看起来像这样：

	try{
		//代码监控区域
	
	}catch(A a1){
		//处理A类型异常
	}catch(B b1){
		//处理B类型异常
	}finally{
		//无论是否异常，都会执行
	}

##finally用来做什么

要把内在之外的资源恢复到它们的初始状态时，就要用到finally子句。  
这种需要清理的资源包括：
已经打开的文件或网络连接等。 

当涉及break continue或者return时，finally子句都会得到执行。


# 异常的限制

当覆盖方法时，只能抛出在基类方法的异常说明里列出的那些异常。